### ISSUE TITLE
Reading a blog?

### ISSUE THREAD

**Issue by ankitjain28may** [itaditya/ncsblog#1]
Which file is for reading a blog, and its url example?

**Comment by itaditya** [comment]
flexBlog.html

All the premade sample json files are in blog/ folder

**Comment by itaditya** [comment]
. es/flexBlog.html

**Comment by ankitjain28may** [comment]
n if its unique link for the post is abc so the url is like this..
.es/flexBlog.html/abc

**Comment by itaditya** [comment]
No it's.... . es/abcBlog.html
