### ISSUE TITLE
Loading a blog from DB

### ISSUE THREAD

**Issue by ankitjain28may** [itaditya/ncsblog#9]
Still i am not getting you, what are you trying to do, I have written a blog, and download its json file and put it in a blogs folder and on loading http://localhost/ncsblog/filename(PHPHBlog.html)
It shows PHPHBlog.html is not found.. so i think everytme a person writes a blog, you need to make a new file for the reading purpose. It is quite wrong.
Accrding to me you should have to make a file fr reading and when a person calls tht file with the unique tag like this i.e http://localhost/ncsblog/(filename.html)/(unique Tag)
then i wil access tht unique tag and finds the respective content from the db and give u its json format to you and u can load it on the reading file.

I hope you understand wht i am trying to say.!!

**Comment by itaditya** [comment]
Yes, you are right, please do that.
